### ISSUE TITLE
Service design guidelines

### ISSUE THREAD

**Issue by campbellfleury** [campbellfleury/A-Spatial-Framework#13]
Outlines the standards a new service should conform to, and the structural considerations required for successful integration to the platform.

**Comment by campbellfleury** [comment]
Suggest the adoption of priciples from the 12 factor app guides: https://12factor.net/ 
What do you guys @braaksman, @braaksman think?

**Comment by braaksman** [comment]
@campbellfleury your experience with Blue Peter makes you better suited to deciding if we adopt this framework. I have read through it and it does make sense, however there are a couple of questions I have with the types of code we develop. 
1. The framework is heavily targeted towards web development/apps, where as the majority of our coding has been in non web based tools, will we have trouble trying to apply some of these steps to the ArcGIS style of tool development?
2. One of the major flaws of ArcGIS, in fact most GIS libraries too, is that they are not implicit. So there is always a set of requirements for each machine to be setup with, before any app/tool can be deployed. We may have to make exceptions for number 2 - Dependencies.
3. Number 3 - Backing Services has suggestions about logging tools, we should implement a industry generated logging system such as python-diamond and Graphite in place of GISToolMetrics.

**Comment by campbellfleury** [comment]
@braaksman yes potentially we will have trouble adopting this framework for the ESRI side of things. I'm running an experiment to determine if feature/map services and geoprocessing services can be deployed and maintained in a manner that aligns with 12factor. 
In terms of logging, our overall framework makes suggestions regarding this so we should look to adopt a form of logging/monitoring that can be language agnostic.
